### ISSUE TITLE
启动成功，但访问7001报internel server error

### ISSUE THREAD

**Issue by alvawu** [cnpm/cnpmcore#257]
按照setup.md指引，用docker方式安装了redis和mysql，然后到项目下npm install, npm run start，提示成功
![image](https://user-images.githubusercontent.com/4371222/177076545-f1ba14aa-f11a-4477-876e-74e6cb1cf879.png)
但是浏览器访问7001的服务，报Internal Server Error, real status: 500
请问要怎么看是什么原因导致？谢谢！

**Comment by alvawu** [comment]
在日志文件里面没找到如下报错

nodejs.Error: Please set config.keys first
    at Application.get keys [as keys] (/apps/node/cnpmcore-main/node_modules/egg/lib/application.js:266:15)
    at Object.get cookies [as cookies] (/apps/node/cnpmcore-main/node_modules/egg/app/extend/context.js:23:66)
    at Object.get [egg-security#CSRF_SECRET] (/apps/node/cnpmcore-main/node_modules/egg-security/app/extend/context.js:91:35)
    at Object.ensureCsrfSecret (/apps/node/cnpmcore-main/node_modules/egg-security/app/extend/context.js:104:13)
    at csrf (/apps/node/cnpmcore-main/node_modules/egg-security/lib/middlewares/csrf.js:15:11)
    at dispatch (/apps/node/cnpmcore-main/node_modules/koa-compose/index.js:42:32)
    at /apps/node/cnpmcore-main/node_modules/koa-compose/index.js:34:12
    at dispatch (/apps/node/cnpmcore-main/node_modules/koa-compose/index.js:42:32)
    at session (/apps/node/cnpmcore-main/node_modules/koa-session/index.js:41:13)
    at dispatch (/apps/node/cnpmcore-main/node_modules/koa-compose/index.js:42:32)

**Comment by killagu** [comment]
这是 eggjs 的配置。按照提示配置在 config.default.js 里。

**Comment by linxiaowu66** [comment]
@killagu 为啥我配置了config.keys还是不能生效，看了下代码生成的run/application_config.json 这个值还是空的？

<img width="470" alt="image" src="https://user-images.githubusercontent.com/13563876/181764555-d6a196e5-fa50-4a20-bc6e-8702d897fbb2.png">


你们文档部署步骤能给详细点吗？

是执行npm run stc:prod 之后 npm run start吗？我自己本地试了npm run dev 是没问题的，但是用start就启动不了了

**Comment by linxiaowu66** [comment]
@fengmk2 @atian25 请问生产环境的部署方式是怎样的？为啥我按照命令来感觉没有成功

**Comment by atian25** [comment]
就是 tsc 后 start，跟 egg 的 ts 开发方式没啥区别

**Comment by linxiaowu66** [comment]
@atian25 但是启动不成功  keys的问题是一个 我强制在node_modules下修改egg/application下勉强绕过去，之后访问又报404了。 用cnpm.org一下子部署就ok了。。。

**Comment by u404** [comment]
同样出现了该问题，配置到config.default.js 的 config.keys 不起作用

**Comment by Scumwong** [comment]
> 

您这个解决了没

**Comment by Scumwong** [comment]
> 同样出现了该问题，配置到config.default.js 的 config.keys 不起作用

您这个解决了没

**Comment by atian25** [comment]
有问题的提交你们的最小化可复现仓库来看看呗

**Comment by linxiaowu66** [comment]
> > 同样出现了该问题，配置到config.default.js 的 config.keys 不起作用
> 
> 您这个解决了没

木有，最后放弃cnpm了，太差劲了。改用maven repo  比这个好用千百倍

**Comment by fengmk2** [comment]
@linxiaowu66 谢谢

**Comment by zzfn** [comment]
同样问题+1

**Comment by pengfeir** [comment]
同样问题+1
