### ISSUE TITLE
EINTEGRITY: 包安装报错

### ISSUE THREAD

**Issue by laoboxie** [cnpm/cnpmcore#321]
搭建的 cnpmcore 从 cnpm.org 同步包，包安装的时候报错 EINTEGRITY 错误：
``` shell
➜  npm-test git:(master) ✗ npm i ini   
npm WARN tarball tarball data for ini@http://localhost:7000/ini/-/ini-3.0.1.tgz (sha512-it4HyVAUTKBc6m8e1iXWvXSTdndF7HbdN713+kvLrymxTaU4AUBWrJ4vEooP+V7fexnVD3LKcBshjGGPefSMUQ==) seems to be corrupted. Trying again.
npm WARN tarball tarball data for ini@http://localhost:7000/ini/-/ini-3.0.1.tgz (sha512-it4HyVAUTKBc6m8e1iXWvXSTdndF7HbdN713+kvLrymxTaU4AUBWrJ4vEooP+V7fexnVD3LKcBshjGGPefSMUQ==) seems to be corrupted. Trying again.
npm ERR! code EINTEGRITY
npm ERR! sha512-it4HyVAUTKBc6m8e1iXWvXSTdndF7HbdN713+kvLrymxTaU4AUBWrJ4vEooP+V7fexnVD3LKcBshjGGPefSMUQ== integrity checksum failed when using sha512: wanted sha512-it4HyVAUTKBc6m8e1iXWvXSTdndF7HbdN713+kvLrymxTaU4AUBWrJ4vEooP+V7fexnVD3LKcBshjGGPefSMUQ== but got sha512-yxMGm6fcTvVTd5aNxfSqVCUFfgyXag8ECrHzwnpqRQu9/bB+kia3cdxOdGiYyi13C2CM96FMcPMVHYeRs2VCZQ==. (92 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2022-09-27T10_00_09_627Z-debug-0.log
```
```shell
0 verbose cli /Users/admin/.nvm/versions/node/v16.15.1/bin/node /Users/admin/.nvm/versions/node/v16.15.1/bin/npm
1 info using npm@8.19.2
2 info using node@v16.15.1
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/Users/admin/.nvm/versions/node/v16.15.1/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/admin/robert/test-projects/npm-test/.npmrc Completed in 0ms
10 timing config:load:project Completed in 4ms
11 timing config:load:file:/Users/admin/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/Users/admin/.nvm/versions/node/v16.15.1/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 11ms
19 timing npm:load:configload Completed in 11ms
20 timing npm:load:mkdirpcache Completed in 1ms
21 timing npm:load:mkdirplogs Completed in 0ms
22 verbose title npm i ini
23 verbose argv "i" "ini"
24 timing npm:load:setTitle Completed in 15ms
25 timing config:load:flatten Completed in 2ms
26 timing npm:load:display Completed in 3ms
27 verbose logfile logs-max:10 dir:/Users/admin/.npm/_logs
28 verbose logfile /Users/admin/.npm/_logs/2022-09-27T10_00_09_627Z-debug-0.log
29 timing npm:load:logFile Completed in 4ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 35ms
33 timing arborist:ctor Completed in 1ms
34 silly logfile start cleaning logs, removing 1 files
35 silly logfile done cleaning log files
36 timing arborist:ctor Completed in 1ms
37 timing idealTree:init Completed in 9ms
38 timing idealTree:userRequests Completed in 2ms
39 silly idealTree buildDeps
40 silly fetch manifest ini@*
41 http fetch GET 200 http://127.0.0.1:7000/ini 26ms (cache revalidated)
42 silly placeDep ROOT ini@3.0.1 OK for: @example/robertxie-test@2.0.3 want: *
43 timing idealTree:#root Completed in 33ms
44 timing idealTree:node_modules/ini Completed in 0ms
45 timing idealTree:buildDeps Completed in 35ms
46 timing idealTree:fixDepFlags Completed in 0ms
47 timing idealTree Completed in 47ms
48 timing reify:loadTrees Completed in 47ms
49 timing reify:diffTrees Completed in 1ms
50 silly reify moves {}
51 timing reify:retireShallow Completed in 1ms
52 timing reify:createSparse Completed in 2ms
53 timing reify:loadBundles Completed in 0ms
54 silly audit bulk request { ini: [ '3.0.1' ] }
55 silly tarball no local data for ini@http://localhost:7000/ini/-/ini-3.0.1.tgz. Extracting by manifest.
56 http fetch POST 404 http://127.0.0.1:7000/-/npm/v1/security/advisories/bulk 8ms
57 silly audit bulk request failed <h1>404 Not Found</h1>
58 http fetch POST 404 http://127.0.0.1:7000/-/npm/v1/security/audits/quick 3ms
59 verbose audit error HttpErrorGeneral: 404 Not Found - POST http://127.0.0.1:7000/-/npm/v1/security/audits/quick
59 verbose audit error     at /Users/admin/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:95:15
59 verbose audit error     at processTicksAndRejections (node:internal/process/task_queues:96:5)
59 verbose audit error     at async Map.[getReport] (/Users/admin/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:335:21)
59 verbose audit error     at async Map.run (/Users/admin/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:106:19) {
59 verbose audit error   headers: [Object: null prototype] {
59 verbose audit error     vary: [ 'Origin' ],
59 verbose audit error     'x-frame-options': [ 'SAMEORIGIN' ],
59 verbose audit error     'x-xss-protection': [ '1; mode=block' ],
59 verbose audit error     'x-content-type-options': [ 'nosniff' ],
59 verbose audit error     'x-download-options': [ 'noopen' ],
59 verbose audit error     'content-type': [ 'text/html; charset=utf-8' ],
59 verbose audit error     'content-length': [ '22' ],
59 verbose audit error     'x-readtime': [ '1.647' ],
59 verbose audit error     date: [ 'Tue, 27 Sep 2022 10:00:09 GMT' ],
59 verbose audit error     connection: [ 'keep-alive' ],
59 verbose audit error     'keep-alive': [ 'timeout=5' ],
59 verbose audit error     'x-fetch-attempts': [ '1' ]
59 verbose audit error   },
59 verbose audit error   statusCode: 404,
59 verbose audit error   code: 'E404',
59 verbose audit error   method: 'POST',
59 verbose audit error   uri: 'http://127.0.0.1:7000/-/npm/v1/security/audits/quick',
59 verbose audit error   body: <Buffer 3c 68 31 3e 34 30 34 20 4e 6f 74 20 46 6f 75 6e 64 3c 2f 68 31 3e>,
59 verbose audit error   pkgid: undefined
59 verbose audit error }
60 silly audit error <h1>404 Not Found</h1>
61 timing auditReport:getReport Completed in 17ms
62 silly audit report null
63 timing reify:audit Completed in 17ms
64 warn tarball tarball data for ini@http://localhost:7000/ini/-/ini-3.0.1.tgz (sha512-it4HyVAUTKBc6m8e1iXWvXSTdndF7HbdN713+kvLrymxTaU4AUBWrJ4vEooP+V7fexnVD3LKcBshjGGPefSMUQ==) seems to be corrupted. Trying again.
65 warn tarball tarball data for ini@http://localhost:7000/ini/-/ini-3.0.1.tgz (sha512-it4HyVAUTKBc6m8e1iXWvXSTdndF7HbdN713+kvLrymxTaU4AUBWrJ4vEooP+V7fexnVD3LKcBshjGGPefSMUQ==) seems to be corrupted. Trying again.
66 timing reify:rollback:createSparse Completed in 2ms
67 timing reify:rollback:retireShallow Completed in 0ms
68 timing command:i Completed in 141105ms
69 verbose stack Error: sha512-it4HyVAUTKBc6m8e1iXWvXSTdndF7HbdN713+kvLrymxTaU4AUBWrJ4vEooP+V7fexnVD3LKcBshjGGPefSMUQ== integrity checksum failed when using sha512: wanted sha512-it4HyVAUTKBc6m8e1iXWvXSTdndF7HbdN713+kvLrymxTaU4AUBWrJ4vEooP+V7fexnVD3LKcBshjGGPefSMUQ== but got sha512-yxMGm6fcTvVTd5aNxfSqVCUFfgyXag8ECrHzwnpqRQu9/bB+kia3cdxOdGiYyi13C2CM96FMcPMVHYeRs2VCZQ==. (92 bytes)
69 verbose stack     at IntegrityStream.[_onEnd] (/Users/admin/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/ssri/lib/index.js:118:19)
69 verbose stack     at IntegrityStream.emit (/Users/admin/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/ssri/lib/index.js:88:19)
69 verbose stack     at IntegrityStream.[maybeEmitEnd] (/Users/admin/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/minipass/index.js:440:12)
69 verbose stack     at IntegrityStream.[emitData] (/Users/admin/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/minipass/index.js:494:25)
69 verbose stack     at IntegrityStream.emit (/Users/admin/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/minipass/index.js:456:25)
69 verbose stack     at IntegrityStream.emit (/Users/admin/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/ssri/lib/index.js:90:18)
69 verbose stack     at IntegrityStream.[flushChunk] (/Users/admin/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/minipass/index.js:368:26)
69 verbose stack     at IntegrityStream.[flush] (/Users/admin/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/minipass/index.js:361:34)
69 verbose stack     at IntegrityStream.[resume] (/Users/admin/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/minipass/index.js:314:18)
69 verbose stack     at IntegrityStream.on (/Users/admin/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/minipass/index.js:414:19)
70 verbose cwd /Users/admin/robert/test-projects/npm-test
71 verbose Darwin 19.6.0
72 verbose node v16.15.1
73 verbose npm  v8.19.2
74 error code EINTEGRITY
75 error sha512-it4HyVAUTKBc6m8e1iXWvXSTdndF7HbdN713+kvLrymxTaU4AUBWrJ4vEooP+V7fexnVD3LKcBshjGGPefSMUQ== integrity checksum failed when using sha512: wanted sha512-it4HyVAUTKBc6m8e1iXWvXSTdndF7HbdN713+kvLrymxTaU4AUBWrJ4vEooP+V7fexnVD3LKcBshjGGPefSMUQ== but got sha512-yxMGm6fcTvVTd5aNxfSqVCUFfgyXag8ECrHzwnpqRQu9/bB+kia3cdxOdGiYyi13C2CM96FMcPMVHYeRs2VCZQ==. (92 bytes)
76 verbose exit 1
77 timing npm Completed in 141204ms
78 verbose unfinished npm timer reify 1664272809726
79 verbose unfinished npm timer reify:unpack 1664272809789
80 verbose unfinished npm timer reifyNode:node_modules/ini 1664272809789
81 verbose code 1
82 error A complete log of this run can be found in:
82 error     /Users/admin/.npm/_logs/2022-09-27T10_00_09_627Z-debug-0.log
```

cnpmcore:  v2.1.1
cos-cnpm: v2.0.1
node: v16.15.1
npm:  v8.19.2

搭建的 cnpmcore，使用cos-cnpm，如果是本地新发布的包，安装没有问题。

请问应该如何排查问题？尝试过清除npm缓存，但是没有效果；也尝试将数据库中的 integrity 改掉，也没有效果。

**Comment by laoboxie** [comment]
目前发现，cos上的tgz文件有问题，文件是损坏的。如果本地使用 fs-cnpm，则没有问题。目前怀疑是cos-cnpm的问题。

![image](https://user-images.githubusercontent.com/23701019/192680098-db942db5-3081-4ee9-b06a-5abd819c4b68.png)

**Comment by Aqiu007** [comment]
我们也出现了这个问题，主要是@babel/下的7.19.3版本的包。

**Comment by laoboxie** [comment]
已定位到是 cos-cnpm 包的bug（https://github.com/cnpm/cos-cnpm/pull/3）。

**Comment by laoboxie** [comment]
> 我们也出现了这个问题，主要是@babel/下的7.19.3版本的包。

我们是所有包都出现这个问题。如果你只是某些包邮问题，可以考虑可能是 bug-versions 认为这些包有 bug，所以被替换成低版本导致哈希校验失败。
