### ISSUE TITLE
handle warning logs on r.cnpmjs.org

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmcore#325]
```
content:2022-10-06 02:58:35,572 WARN 489012 [-/221.180.206.15/b6eca030-44df-11ed-8638-6bc23a04180e/3.269ms POST /public/index.php?s=captcha] nodejs.BadRequestError: invalid overriden method: "__CONSTRUCT"

    at overrideMethod (/home/admin/application/node_modules/_koa-override@3.0.0@koa-override/index.js:33:18)
    at Object.throw (/home/admin/application/node_modules/_koa@2.13.4@koa/lib/context.js:97:11)


content:2022-10-06 02:57:17,002 WARN 489014 [-/221.180.206.15/8817cb90-44df-11ed-9154-395df9c153f0/1.263ms POST /wcm/services/trswcm:SOAPService] nodejs.SyntaxError: Unexpected token < in JSON at position 0, check bodyParser config

content:2022-10-06 02:59:07,366 WARN 489013 [-/221.180.206.15/c9dfb330-44df-11ed-98c1-3399ebac36f6/1.924ms GET /..\pixfir~1\how_to_login.html] nodejs.BadRequestError: Bad Request

```

**Comment by fengmk2** [comment]
override method 忘记了当年为什么会默认开启 https://github.com/eggjs/egg/blob/master/app/middleware/override_method.js

**Comment by fengmk2** [comment]
content:2022-10-05 23:46:27,694 WARN 611197 [-/121.22.26.98/dfc5e2c0-44c4-11ed-a44b-69a25aa32a5b/1.519ms GET /..\..\..\..\..\..\..\..\..\..\..\windows\win.ini] nodejs.BadRequestError: Bad Request
