### ISSUE TITLE
 Please set config.keys first

### ISSUE THREAD

**Issue by zzfn** [cnpm/cnpmcore#345]
```
2022-10-26 20:40:16,552 ERROR 12031 [-/127.0.0.1/-/4ms GET /] nodejs.Error: Please set config.keys first
    at Application.get keys [as keys] (/Users/cc/dev/cnpmcore/node_modules/egg/lib/application.js:269:15)
    at Object.get cookies [as cookies] (/Users/cc/dev/cnpmcore/node_modules/egg/app/extend/context.js:23:66)
    at Object.get [egg-security#CSRF_SECRET] (/Users/cc/dev/cnpmcore/node_modules/egg-security/app/extend/context.js:91:35)
    at Object.ensureCsrfSecret (/Users/cc/dev/cnpmcore/node_modules/egg-security/app/extend/context.js:104:13)
    at csrf (/Users/cc/dev/cnpmcore/node_modules/egg-security/lib/middlewares/csrf.js:15:11)
    at dispatch (/Users/cc/dev/cnpmcore/node_modules/koa-compose/index.js:42:32)
    at /Users/cc/dev/cnpmcore/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cc/dev/cnpmcore/node_modules/koa-compose/index.js:42:32)
    at session (/Users/cc/dev/cnpmcore/node_modules/koa-session/index.js:41:13)
    at dispatch (/Users/cc/dev/cnpmcore/node_modules/koa-compose/index.js:42:32)

pid: 12031
```
```
export default (appInfo: EggAppConfig) => {
  const config = {} as PowerPartial<EggAppConfig>;
  config.keys = '123456';
  config.cnpmcore = {
    name: 'cnpm',
    hooksLimit: 20,
    sourceRegistry: 'https://registry.npmjs.org',
    // upstream registry is base on `cnpmcore` or not
    // if your upstream is official npm registry, please turn it off
    sourceRegistryIsCNpm: false,
    syncUpstreamFirst: false,
    // 3 mins
```

1. git clone https://github.com/cnpm/cnpmcore.git
2. 修改mysql redis keys
3. 执行 npm run tsc:prod
4. npm run start.

**Comment by elrrrrrrr** [comment]
可以先关闭一下 csrf 插件
```javascript
// config.default.ts
  config.security = {
    csrf: {
      enable: false,
    },
  };
```

**Comment by zzfn** [comment]
> 可以先关闭一下 csrf 插件
> 
> ```js
> // config.default.ts
>   config.security = {
>     csrf: {
>       enable: false,
>     },
>   };
> ```

关掉了，试了一下 npm run tsc 后可以 npm run tsc:prod 后不行

**Comment by bqxu** [comment]
遇到一样的问题，体验不佳。 文档可以在完善一点吧。。。。

**Comment by fengmk2** [comment]
非常抱歉，目前处于高速迭代期，并且我们只针对有 egg 经验的人员才能有效沟通。对于零经验的开发者来说，基本是无法部署起来的。

**Comment by pengfeir** [comment]
同样的问题，dev可以跑起来，start跑起来不报错，打开后
<img width="457" alt="image" src="https://user-images.githubusercontent.com/22837913/204501455-2b41fed7-f4e9-4096-8bbe-85dc372f3818.png">

**Comment by atian25** [comment]
start 模式先用 tsc， cnpmcore 是一个高级使用场景，请先去熟悉 egg 的 ts 开发。
start 模式先用 tsc， cnpmcore 是一个高级使用场景，请先去熟悉 egg 的 ts 开发。
start 模式先用 tsc， cnpmcore 是一个高级使用场景，请先去熟悉 egg 的 ts 开发。
start 模式先用 tsc， cnpmcore 是一个高级使用场景，请先去熟悉 egg 的 ts 开发。
start 模式先用 tsc， cnpmcore 是一个高级使用场景，请先去熟悉 egg 的 ts 开发。
start 模式先用 tsc， cnpmcore 是一个高级使用场景，请先去熟悉 egg 的 ts 开发。
start 模式先用 tsc， cnpmcore 是一个高级使用场景，请先去熟悉 egg 的 ts 开发。
start 模式先用 tsc， cnpmcore 是一个高级使用场景，请先去熟悉 egg 的 ts 开发。
start 模式先用 tsc， cnpmcore 是一个高级使用场景，请先去熟悉 egg 的 ts 开发。

**Comment by bqxu** [comment]
抱歉，忽略了ts开发 还需要 tsc ，正常都是在 start 、build 等过程，自动执行了 tsc ，或者使用ts-node， 需要手动执行这点，感觉可以优化一下。

**Comment by atian25** [comment]
开发环境可以用 ts-node，但正式环境没办法自动做，因为正式环境一般都是在构建里面里面 tsc 然后打包成为产物，再丢给部署流程去发布，不会再服务器上再去 tsc 的。
