### ISSUE TITLE
适配 npm v9 的命令数据更新

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmcore#348]
https://github.blog/changelog/2022-10-24-npm-v9-0-0-released/

login and adduser are now separate commands that send different data to the registry.

## login with web

```
request:

POST /-/v1/login
body: {
  hostname: string,
  create: true | false,
}

response:

{
  doneUrl, loginUrl
}
```

check doneUrl

```
GET doneUrl

status: 200
{ token }

status: 202
`retry-after` header in second
```

**Comment by fengmk2** [comment]
https://github.com/npm/cli/pull/5550

**Comment by fengmk2** [comment]
实现 login with web

**Comment by fengmk2** [comment]
npm login

```
npm login --registry=https://registry.npmmirror.com --verbose                                                                                         ∞
npm verb cli /.nvs/node/18.12.0/arm64/bin/node /.npm-global/bin/npm
npm info using npm@9.0.1
npm info using node@v18.12.0
npm verb title npm login
npm verb argv "login" "--registry" "https://registry.npmmirror.com" "--loglevel" "verbose"
npm verb logfile logs-max:10 dir:/.npm/_logs/2022-10-28T01_32_03_071Z-
npm verb logfile /.npm/_logs/2022-10-28T01_32_03_071Z-debug-0.log
npm notice Log in on https://registry.npmmirror.com/
npm verb web login before first POST
npm http fetch POST 404 https://registry.npmmirror.com/-/v1/login 169ms
npm verb stack WebLoginNotSupported: Web login not supported
npm verb stack     at /.npm-global/lib/node_modules/npm/node_modules/npm-profile/lib/index.js:96:13
npm verb stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm verb stack     at async Object.login (//.npm-global/lib/node_modules/npm/lib/utils/auth.js:47:11)
npm verb stack     at async Login.exec (/.npm-global/lib/node_modules/npm/lib/commands/login.js:35:35)
npm verb stack     at async module.exports (/.npm-global/lib/node_modules/npm/lib/cli.js:133:5)
npm verb statusCode 404
npm verb cwd /git/github.com/cnpm/cnpm
npm verb Darwin 21.6.0
npm verb node v18.12.0
npm verb npm  v9.0.1
npm ERR! code ENYI
npm ERR! Web login not supported
npm verb exit 1
npm verb code 1
```

**Comment by fengmk2** [comment]
webAuth 实现 https://github.com/npm/npm-profile/blob/main/lib/index.js#L55

**Comment by fengmk2** [comment]
这样看来好像得先有一个 web 登录界面😭

**Comment by MondoGao** [comment]
> 

哈哈，外网应该不需要，内网直接跳登陆服务回来直接转发就好（

**Comment by fengmk2** [comment]
@MondoGao 哈哈，不是所有私有部署都会包装一下 npm 的，很多还是直接使用 npm 修改 registry 来使用。

**Comment by fengmk2** [comment]
使用 authing.cn 的能力，结合 tegg 的 module 能力，做一个 authing module。

**Comment by fengmk2** [comment]
```bash
npm http fetch POST 200 https://registry.npmjs.org/-/v1/login 893ms
npm verb web auth got response {
npm verb web auth   loginUrl: 'https://www.npmjs.com/login?next=/login/cli/xxxxx,
npm verb web auth   doneUrl: 'https://registry.npmjs.org/-/v1/done?sessionId=xxx'
npm verb web auth }
npm verb web auth opening url pair
Login at:
https://www.npmjs.com/login?next=/login/cli/cf7c0cda-8e88-4684-b905-34a53823cc91
Press ENTER to open in the browser...npm http fetch GET 202 https://registry.npmjs.org/-/v1/done?sessionId=npm_*** 268ms
npm http fetch GET 202 https://registry.npmjs.org/-/v1/done?sessionId=npm_*** 268ms
npm http fetch GET 202 https://registry.npmjs.org/-/v1/done?sessionId=npm_*** 266ms
```

登录成功的界面提示
![image](https://user-images.githubusercontent.com/156269/213907968-f1ab95e2-4743-4fa5-80e7-362ac0fc435b.png)

**Comment by fengmk2** [comment]
baseauth 搞定 
![image](https://user-images.githubusercontent.com/156269/220317360-ea23e2ce-c9ae-44a7-99c8-b06d6f22259e.png)

接下来需要做一个 authing.cn 的 示例

**Comment by dennisleung** [comment]
npm v9+版本的login请求体已经没有hostname参数了，见[npm-profile源码](https://github.com/npm/npm-profile/blob/main/lib/index.js)。WebAuthController中的LoginRequestRule是不是应该调整成这样比较好？
``` typescript
const LoginRequestRule = Type.Object({
  // cli 所在机器的 hostname，NPM9+开始去掉
  hostname: Type.Optional(Type.String({ minLength: 1, maxLength: 100 })),
});
```

**Comment by fengmk2** [comment]
> npm v9+版本的login请求体已经没有hostname参数了，见[npm-profile源码](https://github.com/npm/npm-profile/blob/main/lib/index.js)。WebAuthController中的LoginRequestRule是不是应该调整成这样比较好？
> 
> ```ts
> const LoginRequestRule = Type.Object({
>   // cli 所在机器的 hostname，NPM9+开始去掉
>   hostname: Type.Optional(Type.String({ minLength: 1, maxLength: 100 })),
> });
> ```

可以来一个 pr 修复

**Comment by fengmk2** [comment]
@dennisleung This has already been fixed — `hostname` is already `Type.Optional` in the current code:

```typescript
const LoginRequestRule = Type.Object({
  // cli 所在机器的 hostname，最新版本 npm cli 已经不会上报 hostname
  hostname: Type.Optional(Type.String({ minLength: 1, maxLength: 100 })),
});
```

See [app/port/webauth/WebauthController.ts#L41-L43](https://github.com/cnpm/cnpmcore/blob/master/app/port/webauth/WebauthController.ts#L41-L43).
