### ISSUE TITLE
Error: ER_DATA_TOO_LONG: Data too long for column 'name' at row 1

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmcore#36]
```log
2021-12-14 22:50:16,434 ERROR 92622 [Job#163949322173616956023029765728591] /home/admin/application/app/schedule/SyncPackageWorker.js execute failed, used 194696ms. Error: ER_DATA_TOO_LONG: Data too long for column 'name' at row 1
    at Query.Sequence._packetToError (/home/admin/application/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/admin/application/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/home/admin/application/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/admin/application/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/admin/application/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/admin/application/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/admin/application/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/admin/application/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Protocol._enqueue (/home/admin/application/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:144:48)
    at PoolConnection.query (/home/admin/application/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:198:25)
    at /home/admin/application/node_modules/_leoric@1.15.0@leoric/src/drivers/mysql/index.js:81:18
    at new Promise (<anonymous>)
    at MysqlDriver.query (/home/admin/application/node_modules/_leoric@1.15.0@leoric/src/drivers/mysql/index.js:80:21)
    at Spell.ignite (/home/admin/application/node_modules/_leoric@1.15.0@leoric/src/spell.js:434:37)
    at Spell.then (/home/admin/application/node_modules/_leoric@1.15.0@leoric/src/spell.js:451:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ER_DATA_TOO_LONG',
  errno: 1406,
  sqlMessage: "Data too long for column 'name' at row 1",
  sqlState: '22001',
  index: 0,
  sql: "INSERT INTO `dists` (`gmt_create`, `gmt_modified`, `dist_id`, `name`, `path`, `size`, `shasum`, `integrity`) VALUES ('2021-12-14 22:50:16.377', '2021-12-14 22:50:16.377', '61b8af28489aa269cfabad58', 'solid-client-0.0.2-dependabotnpmandyarnwebsitedocusauruspreset-classic-200-alpha61-192892303-618.0.tgz', '/packages/@inrupt/solid-client/0.0.2-dependabotnpmandyarnwebsitedocusauruspreset-classic-200-alpha61-192892303-618.0/solid-client-0.0.2-dependabotnpmandyarnwebsitedocusauruspreset-classic-200-alpha61-192892303-618.0.tgz', 298974, '716ede0ed0df5d248fff22f8ff598e7fd49a75ce', 'sha512-pkAx/F0mtrSyfNTNgLKSgUN3hchxZi5Iz0RD8Wec6sNgwydC6YI3nXFWcYRB9hdPP5jhmiaBtEVc3DkYYtNEZQ==')"
```

```sql
INSERT INTO `dists` (`gmt_create`, `gmt_modified`, `dist_id`, `name`, `path`, `size`, `shasum`, `integrity`) 
VALUES ('2021-12-14 22:50:16.377', '2021-12-14 22:50:16.377', '61b8af28489aa269cfabad58', 'solid-client-0.0.2-dependabotnpmandyarnwebsitedocusauruspreset-classic-200-alpha61-192892303-618.0.tgz', 
'/packages/@inrupt/solid-client/0.0.2-dependabotnpmandyarnwebsitedocusauruspreset-classic-200-alpha61-192892303-618.0/solid-client-0.0.2-dependabotnpmandyarnwebsitedocusauruspreset-classic-200-alpha61-192892303-618.0.tgz', 
298974, 
'716ede0ed0df5d248fff22f8ff598e7fd49a75ce', 'sha512-pkAx/F0mtrSyfNTNgLKSgUN3hchxZi5Iz0RD8Wec6sNgwydC6YI3nXFWcYRB9hdPP5jhmiaBtEVc3DkYYtNEZQ==')
```

**Comment by fengmk2** [comment]
'solid-client-0.0.2-dependabotnpmandyarnwebsitedocusauruspreset-classic-200-alpha61-192892303-618.0.tgz'.length
102

**Comment by fengmk2** [comment]
将 path 改成 ascii，这样索引可以到 767 个字符

> InnoDB has a maximum index length of 767 bytes for tables that use COMPACT or REDUNDANT row format, so for utf8mb3 or utf8mb4 columns, you can index a maximum of 255 or 191 characters, respectively.


```sql
CREATE TABLE `dists` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'primary key',
  `gmt_create` datetime(3) NOT NULL COMMENT 'create time',
  `gmt_modified` datetime(3) NOT NULL COMMENT 'modified time',
  `dist_id` varchar(24) COLLATE utf8_unicode_ci NOT NULL COMMENT 'dist id',
  `name` varchar(220) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT 'dist name',
  `path` varchar(767) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL COMMENT 'access path',
  `size` int(10) unsigned NOT NULL COMMENT 'file size',
  `shasum` varchar(512) COLLATE utf8_unicode_ci NOT NULL COMMENT 'dist shasum',
  `integrity` varchar(512) COLLATE utf8_unicode_ci NOT NULL COMMENT 'dist integrity',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dist_id` (`dist_id`),
  UNIQUE KEY `uk_path` (`path`)
) ENGINE=InnoDB AUTO_INCREMENT=566116 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='dist info'
```
