### ISSUE TITLE
nodejs.RangeError: Maximum call stack size exceeded by RegExp.test

### ISSUE THREAD

**Issue by Liar0320** [cnpm/cnpmcore#388]
When I publish the package
```npm notice name:          @xxx/xxxx-public                 
npm notice version:       1.0.8                                   
npm notice filename:      @xxxx/xxxx-public-1.0.8.tgz       
npm notice package size:  3.8 MB                                  
npm notice unpacked size: 7.2 MB                                  
npm notice shasum:        ced9a1ec80f2108092bd270bcb53a399d2d9fd6a
npm notice integrity:     sha512-6bYYN8N6TwZ2H[...]AdT9K8HIV80zw==
npm notice total files:   421                                     
npm notice 
npm notice Publishing to http://xxx:7001/
npm ERR! code E500
npm ERR! 500 Internal Server Error - PUT http://xxxxx:7001/@xxxx%xxxx-public - Maximum call stack size exceeded
```
when I delete img assets, it will work well
<img width="538" alt="image" src="https://user-images.githubusercontent.com/27603449/216220778-b5931cf0-5e55-4cf2-a29d-a7e01fe06ebb.png">

```
npm notice === Tarball Details === 
npm notice name:          @xxx/xxx-public                 
npm notice version:       1.0.8                                   
npm notice filename:      @xxxx/xxx-public-1.0.8.tgz       
npm notice package size:  1.7 MB                                  
npm notice unpacked size: 4.4 MB                                  
npm notice shasum:        7b45e5391b36345cf0280adbf387d3da71466f5a
npm notice integrity:     sha512-1X2lE1PtJ1Auz[...]NA/SjAU+UI5DA==
npm notice total files:   413                                     
npm notice 
npm notice Publishing to http://xxxxx:7001/
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT http://xxxx:7001/@xxxx%xxx-public  - [FORBIDDEN] Can't modify pre-existing version:
```

**Comment by fengmk2** [comment]
500 Internal Server Error ，可以看看服务端的 common-error log 日志，里面有错误堆栈。

**Comment by Liar0320** [comment]
> 500 Internal Server Error ，可以看看服务端的 common-error log 日志，里面有错误堆栈。

```javascript

2023-02-02 11:10:26,699 ERROR 15620 [63aab0630e740861ed2e6639/125.118.63.94/24015a60-a2a7-11ed-8a5d-db233c14b960/1801.666ms PUT /@washeng%2fnearhub-public] nodejs.RangeError: Maximum call stack size exceeded
    at RegExp.test (<anonymous>)
    at SavePackageVersionController.save (/root/soft/cnpmcore/app/port/controller/package/SavePackageVersionController.ts:133:92)
    at Object.<anonymous> (/root/soft/cnpmcore/node_modules/@eggjs/tegg-controller-plugin/lib/impl/http/HTTPMethodRegister.ts:97:34)
    at Object.callFn (/root/soft/cnpmcore/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/root/soft/cnpmcore/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/root/soft/cnpmcore/node_modules/@eggjs/router/node_modules/koa-compose/index.js:44:32)
    at next (/root/soft/cnpmcore/node_modules/@eggjs/router/node_modules/koa-compose/index.js:45:18)
    at AlwaysAuth (/root/soft/cnpmcore/app/port/middleware/AlwaysAuth.ts:13:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

pid: 15620
hostname: jk
```

应该就这一条错误日志，不处理也没事，我把这个包的图片压缩了下就没什么问题了。

**Comment by fengmk2** [comment]
https://github.com/cnpm/cnpmcore/blob/master/app/port/controller/package/SavePackageVersionController.ts#L133

@Liar0320 感谢反馈，这里确实会有一些问题，这种表达式执行出问题后报的异常，应该跟字符串大小有关。我会先尝试重现看看如何修复。
