### ISSUE TITLE
centos 下执行 npm run dev 报错

### ISSUE THREAD

**Issue by yuanzhaoK** [cnpm/cnpmcore#415]
<img width="1662" alt="image" src="https://user-images.githubusercontent.com/124442084/222037222-11c46d07-aca5-455f-8938-88076a583833.png">

**Comment by fengmk2** [comment]
如果是在服务器部署，或者 tsc 之后运行，需要执行 npm start 脚本来启动 https://github.com/cnpm/cnpmcore/blob/master/package.json#L52

npm run dev 走了 egg-bin 会冲突。

**Comment by yuanzhaoK** [comment]
我使用了npm start的来启动，但是日志里报了这个错

2023-03-01 13:48:11,096 ERROR 7456 nodejs.Error: [NFSAdapter] Can't use local fs NFS on production env
    at NFSClientAdapter.init (/root/cnpmcore/app/infra/NFSClientAdapter.ts:40:15)
    at EggObjectImpl.init (/root/cnpmcore/node_modules/@eggjs/tegg-runtime/src/impl/EggObjectImpl.ts:67:32)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at createObject (/root/cnpmcore/node_modules/@eggjs/tegg-runtime/src/impl/EggObjectImpl.ts:111:5)
    at Function.createObject (/root/cnpmcore/node_modules/@eggjs/tegg-runtime/src/factory/EggObjectFactory.ts:41:17)
    at ModuleLoadUnitInstance.getOrCreateEggObject (/root/cnpmcore/node_modules/@eggjs/tegg-runtime/src/impl/ModuleLoadUnitInstance.ts:77:21)
    at ModuleLoadUnitInstance.init (/root/cnpmcore/node_modules/@eggjs/tegg-runtime/src/impl/ModuleLoadUnitInstance.ts:49:7)
    at Function.createLoadUnitInstance (/root/cnpmcore/node_modules/@eggjs/tegg-runtime/src/factory/LoadUnitInstanceFactory.ts:41:9)
    at ModuleHandler.init (/root/cnpmcore/node_modules/@eggjs/tegg-plugin/lib/ModuleHandler.ts:37:26)
    at App.didLoad (/root/cnpmcore/node_modules/@eggjs/tegg-plugin/app.ts:39:5)

**Comment by ChrisSong1994** [comment]
> 
生产环境不允许存在本地，可以看下这个
https://github.com/cnpm/cnpmjs.org/wiki/NFS-Guide

**Comment by ChrisSong1994** [comment]
> 我使用了npm start的来启动，但是日志里报了这个错
> 
> 2023-03-01 13:48:11,096 ERROR 7456 nodejs.Error: [NFSAdapter] Can't use local fs NFS on production env at NFSClientAdapter.init (/root/cnpmcore/app/infra/NFSClientAdapter.ts:40:15) at EggObjectImpl.init (/root/cnpmcore/node_modules/@eggjs/tegg-runtime/src/impl/EggObjectImpl.ts:67:32) at processTicksAndRejections (node:internal/process/task_queues:95:5) at createObject (/root/cnpmcore/node_modules/@eggjs/tegg-runtime/src/impl/EggObjectImpl.ts:111:5) at Function.createObject (/root/cnpmcore/node_modules/@eggjs/tegg-runtime/src/factory/EggObjectFactory.ts:41:17) at ModuleLoadUnitInstance.getOrCreateEggObject (/root/cnpmcore/node_modules/@eggjs/tegg-runtime/src/impl/ModuleLoadUnitInstance.ts:77:21) at ModuleLoadUnitInstance.init (/root/cnpmcore/node_modules/@eggjs/tegg-runtime/src/impl/ModuleLoadUnitInstance.ts:49:7) at Function.createLoadUnitInstance (/root/cnpmcore/node_modules/@eggjs/tegg-runtime/src/factory/LoadUnitInstanceFactory.ts:41:9) at ModuleHandler.init (/root/cnpmcore/node_modules/@eggjs/tegg-plugin/lib/ModuleHandler.ts:37:26) at App.didLoad (/root/cnpmcore/node_modules/@eggjs/tegg-plugin/app.ts:39:5)

生产环境不允许存在本地，可以看下这个
https://github.com/cnpm/cnpmjs.org/wiki/NFS-Guide

**Comment by coolyuantao** [comment]
1. 如果仅是想本地调试，npm run clean 下环境就不会你的第一个问题。
2. 如果仅是想验证下功能的话，可以手动配置下NFS，但生产环境用这个怕是后面随时崩了。
```
  config.nfs = {
    client: new FSClient({ dir: join(dataDir, 'nfs') }),
  };
```
3. 还是另起个Egg项目，安装 cnpmcore 依赖，这样好用一点

**Comment by yuanzhaoK** [comment]
> 

了解
