### ISSUE TITLE
[FORBIDDEN] Can't modify pre-existing version: xxx@0.6.57

### ISSUE THREAD

**Issue by yang200258** [cnpm/cnpmcore#729]
我发布一个包的时候，提示：
`Publishing to http:$REGISTRY with tag latest and default access
npm http fetch PUT 403 http:$REGISTRY xxx 74374ms attempt #3
npm verb stack HttpErrorGeneral: 403 Forbidden - PUT http:$REGISTRY xxxxx- [FORBIDDEN] Can't modify pre-existing version: xxxx@0.6.57
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:95:15
npm verb stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm verb stack     at async publish (/usr/local/lib/node_modules/npm/node_modules/libnpmpublish/lib/publish.js:53:15)
npm verb stack     at async otplease (/usr/local/lib/node_modules/npm/lib/utils/otplease.js:4:12)
npm verb stack     at async Publish.exec (/usr/local/lib/node_modules/npm/lib/commands/publish.js:126:7)
npm verb stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli-entry.js:61:5)
npm verb statusCode 403
npm verb pkgid xxx@0.6.57`

但是在查询版本时候显示并没有0.6.57版本
<img width="489" alt="image" src="https://github.com/user-attachments/assets/f9a8d16d-99b0-4ee0-b37e-f0fadf8b2649">
从数据库查又有：
<img width="1136" alt="image" src="https://github.com/user-attachments/assets/f56962eb-ebdd-4e90-a122-2a2226171cfd">

**Comment by elrrrrrrr** [comment]
这个包是私有源上的包吗？ db 内数据看起来是脏数据？

**Comment by yang200258** [comment]
> 这个包是私有源上的包吗？ db 内数据看起来是脏数据？

对的，是私有源的，脏数据是怎么看出来的？
